
# Site settings
title: jiangwei
email: 2663282076@qq.com
description: "jiangwei"


# Team names, titles and social links
people:
- name: 蒋伟
  pic: 1
  position: UI设计师/前端工程师
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: 李庆敏
  pic: 2
  position: UI设计师
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: 毛希
  pic: 3
  position: UI设计师/铁路
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: csdn
    url: https://blog.csdn.net/weixin_43324273
  - title: zcool
    url: https://www.zcool.com.cn/u/19546636
  - title: xiao-wei-1998
    url: https://github.com/xiao-wei-1998

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty

#百度统计
#使用博客模板请去掉或者更换id
baidu:
  - id: 71ee328a906d66c3774e4550d60775bd