url: https://xiao-wei-1998.github.io/jiang.github.io/

# Site settings
title: DIV网络工作室
email: 2663282076@qq.com
description: "DIV网络工作室"


# Team names, titles and social links
people:
- name: 蒋伟
  pic: 1
  position: UI设计师/前端工程师
  social:
    - title: csdn
      url: https://blog.csdn.net/weixin_43324273
    - title: zcool
      url: https://www.zcool.com.cn/u/19546636
    - title: github
      url: https://github.com/xiao-wei-1998

- name: 毛希宸
  pic: 2
  position: UI设计/平面设计/活动策划
  social:
    - title: csdn
      url: https://www.zcool.com.cn/u/19905586
    - title: zcool
      url: https://www.zcool.com.cn/u/19905586
    - title: github
      url: https://github.com/xiao-wei-1998

- name: 曹红延
  pic: 3
  position: UI设计师/前端工程师
  social:
    - title: csdn
      url: https://blog.csdn.net/weixin_43324273
    - title: zcool
      url: https://www.zcool.com.cn/u/19546636
    - title: github
      url: https://github.com/xiao-wei-1998



# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: csdn
    url: https://blog.csdn.net/weixin_43324273
  - title: zcool
    url: https://www.zcool.com.cn/u/19546636
  - title: github
    url: https://github.com/xiao-wei-1998

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty

#百度统计
#使用博客模板请去掉或者更换id
baidu:
  - id: 090ea5c73050ba7866b80c8b3e7614e8