url: https://xiao-wei-1998.github.io/jiang.github.io/

# Site settings
title: DIV网络工作室
email: 2663282076@qq.com
description: "DIV网络工作室"


# Team names, titles and social links
people:
- name: 蒋伟
  pic: 1
  position: UI设计师/前端工程师
  social:
    - title: qq
      url: http://wpa.qq.com/msgrd?v=3&uin=2663282076&site=qq&menu=yes
    - title: weixin
      url: https://mp.weixin.qq.com/mp/profile_ext?action=home&__biz=MzIwMjkyNDAxOA==#wechat_redirect
    - title: github
      url: https://github.com/xiao-wei-1998

- name: 毛希宸
  pic: 2
  position: 平面|UI设计/活动策划
  social:
    - title: qq
      url: http://wpa.qq.com/msgrd?v=3&uin=744946911&site=qq&menu=yes
    - title: weixin
      url: https://mp.weixin.qq.com/mp/profile_ext?action=home&__biz=MzIwMjkyNDAxOA==#wechat_redirect
    - title: github
      url: https://github.com/xiao-wei-1998

- name: 曹红延
  pic: 3
  position: UI设计师/前端工程师
  social:
    - title: qq
      url: http://wpa.qq.com/msgrd?v=3&uin=2663282076&site=qq&menu=yes
    - title: weixin
      url: https://mp.weixin.qq.com/mp/profile_ext?action=home&__biz=MzIwMjkyNDAxOA==#wechat_redirect
    - title: github
      url: https://github.com/xiao-wei-1998



# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: qq
    url: http://wpa.qq.com/msgrd?v=3&uin=2663282076&site=qq&menu=yes
  - title: weixin
    url: https://mp.weixin.qq.com/mp/profile_ext?action=home&__biz=MzIwMjkyNDAxOA==#wechat_redirect
  - title: github
    url: https://github.com/xiao-wei-1998

# Postal address (add as many lines as necessary)
address:
  - line: 安徽省合肥市

# Build settings
markdown: kramdown
permalink: pretty

#百度统计
#使用博客模板请去掉或者更换id
baidu:
  - id: 090ea5c73050ba7866b80c8b3e7614e8